<?php 
// làm vi?c v?i hook help
function first_help($path, $arg) {
    if ($path == 'admin/help#first') {
        return t('A demonstration module.');
    }
}
// làm vi?c v?i hook block
/**
* Implements hook_block_info().
*/
function first_block_info() {
    $blocks = array();
        $blocks['list_modules'] = array(
            'info' => t('A listing of all of the enabled modules.'),
            'cache' => DRUPAL_NO_CACHE,
        );
    return $blocks;
}
// làm vi?c v?i hook view
/**
* Implements hook_block_view().
*/
function first_block_view($block_name = '') {
    if ($block_name == 'list_modules') {
        $list = module_list();
        $theme_args = array('items' => $list, 'type' => 'ol');
        $content = theme('item_list', $theme_args);
        $block = array(
            'subject' => t('Enabled Modules'),
            'content' => $content,
        );
        return $block;
    }
}


?>